project:
  type: website
  output-dir: docs

website:
  site-url: https://www.elginakin.github.io/
  favicon: "images/logos/IMG_0926.PNG"
  repo-url: https://github.com/elginakin/elginakin.github.io
  repo-actions: [edit, source, issue]
  navbar:
    logo: "images/logos/IMG_0926.PNG"
    right:
      - text: research
        href: research/index.qmd
      - text: papers
        href: papers/index.qmd
      - text: posts
        href: posts/index.qmd
      - text: cv
        href: cv/AkinE_CV_20260519.pdf
    tools:
      - icon: github
        href: https://github.com/elginakin/elginakin.github.io
      - icon: twitter
        href: https://twitter.com/cxclgin
        text: Twitter
      - icon: envelope
        href: mailto:eakin1@jhmi.edu
  
  page-footer:
    background: light
    left: "&copy; Copyright 2022, Elgin Akin"
    right: "This page is built with ♥ and [Quarto](https://quarto.org/)."

format:
  html:
    theme: Litera
    monobackgroundcolor: '#D3CABA'
    css: styles.css
    mainfont: Helvetica
    sidebar: false
    toc: true
    highlight-style: github

    

