project:
  type: website
  output-dir: docs

website:
  site-url: https://www.elginakin.github.io/
  favicon: "images/logos/IMG_0926.PNG"
  navbar:
    logo: "images/logos/IMG_0926.PNG"
    right:
      - href: index.qmd
        text: home
      - text: research
        href: research/index.qmd
      - text: posts
        href: posts/index.qmd
      - text: cv
  announcement: 
    icon: virus
    dismissable: true
    content: "**Here at [ASV 2025](https://asv.org/asv2025/)?** - Let's get a coffee! Reach out via Whova, email or BlueSky."
    type: danger
    position: below-navbar
    tools:
      - icon: github
        href: https://github.com/elginakin/
      - icon: twitter
        href: https://twitter.com/cxclgin
        text: Twitter
      - icon: envelope
        href: eakin1@jhmi.edu
  
  page-footer:
    background: light
    left: "&copy; Copyright 2022, Elgin Akin"
    right: "This page is built with ♥ and [Quarto](https://quarto.org/)."

format:
  html:
    theme: Litera
    monobackgroundcolor: '#D3CABA'
    css: styles.css
    mainfont: Nunito
    sidebar: false
    toc: true

    

